#!/usr/bin/env bash
# Install load balancer

# Colors for output
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and doing some minor checks...${reset}\n"

function install() {
    command -v "$1" &> /dev/null

    # shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: ${brown}$1${reset}\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${green}${1} is already installed.${reset}\n"
    fi
}

install haproxy # Install HAproxy

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# HAproxy server configuration
server_config=$(cat <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    timeout http-request 10s
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend th3gr00t-tech-frontend
    bind *:80
    default_backend th3gr00t-tech-backend

backend th3gr00t-tech-backend
    balance roundrobin
    server 453-web-01 35.243.128.200:80 check
    server 453-web-02 3.239.120.96:80 check
EOF
)

# Apply the configuration
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAproxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAproxy to apply the new configuration
if ! pgrep -x "haproxy" > /dev/null; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

# Print success message
echo -e "${green}HAproxy is successfully installed and running.${reset}\n"
