#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.

# Initialize the counter variable
counter=1

# Start the while loop
while [ $counter -le 10 ]
do
  # Print "Best School"
  echo "Best School"

  # Increment the counter
  counter=$((counter + 1))
done

