#!/bin/bash

# Set up variables
KEY_NAME="school"
PASSPHRASE="betty"
BITS=4096

# Generate RSA key pair
echo "Generating public/private rsa key pair."
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N $PASSPHRASE

# Output the completion message
echo "Your identification has been saved in $KEY_NAME."
echo "Your public key has been saved in $KEY_NAME.pub."

